### ISSUE TITLE
[BUG 1.16.5] After the player's death, the crafts in the workbench fly off and are not issued.

### ISSUE THREAD

**Issue by MrJorman** [Loli-Server/LoliServer1.16#122] opened 2021-08-19 11:02 UTC
Minecraft Version(我的世界版本) : 1.16.5

LoliServer buildVersion(构建版本) : build 55

Operating System(操作系统) : Windows 10 (64 bit)

Logs : no logs

Mod list(模组列表) : Abnormals+Aurora mods

Plugin list(插件列表) : https://paste.ubuntu.com/p/VryBXfHG8Y/

Description of issue(描述) : After the player's death, the crafts in the workbench fly off and are not issued.

**Comment by XionioXMaster** [comment] 2021-08-19 16:25
Nothing that there are more mods on your server than indicated in the topic?

**Comment by Kotori0629** [comment] 2021-09-07 08:50
Duplicate of #142

**Closed by Kotori0629** 2021-09-07 08:50 UTC
Labels: Wait
