### ISSUE TITLE
[1.16.5 BUG] World_The_End spawn more platforms

### ISSUE THREAD

**Issue by MrJorman** [Loli-Server/LoliServer1.16#136] opened 2021-09-04 13:33 UTC
Sorry, I'll move away from the template, but I'm using the latest version of your kernel and the bug is that players moving to world_the_end constantly create obsidian platforms all over the ender world, there are a lot of them. Can you fix it?

**Comment by Kotori0629** [comment] 2021-09-05 11:35
Is this really a kernel problem?

**Comment by MrJorman** [comment] 2021-09-05 15:57
yes.

**Comment by XionioXMaster** [comment] 2021-09-10 13:49
> Is this really a kernel problem?

I cannot reproduce

**Comment by Kotori0629** [comment] 2021-09-10 13:50
> > Is this really a kernel problem?
> 
> I cannot reproduce

Yes.. I cannot reproduce too..

**Comment by XionioXMaster** [comment] 2021-09-18 13:05
> > > Is this really a kernel problem?
> > 
> > 
> > I cannot reproduce
> 
> Yes.. I cannot reproduce too..

**Endergetic Expansion**

It can create a platform if you use / world DIM1 via essentails, this is on the side of the mod, I guess you can close it.

**Closed** 2021-09-24 04:58 UTC
Labels: Wait
