### ISSUE TITLE
[1.16] Mod chests cannot display correctly after crafting

### ISSUE THREAD

**Issue by XionioXMaster** [Loli-Server/LoliServer1.16#134] opened 2021-08-30 20:15 UTC
**Minecraft Version(我的世界版本) :** 1.16.5

**LoliServer buildVersion(构建版本) :** Provide LoliServer  buildVersion: "LoliServer-1.16.5-60-server.jar"

**Operating System(操作系统) :** Unbuntu 20
**Concerned mod / plugin(有关的插件/Mod) :** Provide mod / plugin name and download link if possible

**Logs :** Nope

**Steps to Reproduce(复现步骤) :**
 1. 

https://user-images.githubusercontent.com/86433158/131399577-ea0924b1-53f2-4cde-a74b-75776381b8f2.mp4

 2. For example, I took a chest from the Better End mod, but in other mods it still does not work correctly, thanks for your work)

**Comment by Kotori0629** [comment] 2021-09-04 12:30
What's your mods? plugins?

**Comment by Kotori0629** [comment] 2021-09-07 08:48
Duplicate of #142

**Closed by Kotori0629** 2021-09-07 08:48 UTC
Labels: Wait
